[tool.poetry]
name = "webp"
version = "0.1.0"
description = ""
authors = ["richard.gong <richard.gong@robinhood.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.9"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
